### ISSUE TITLE
Conflict build process when used with `build_runner`

### ISSUE THREAD

**Issue by hiaw** [timfreiheit/r_flutter#14]
I was trying to do JSON parsing and the recommended way uses `build_runner`. But after `build_runner` ran, the asset.dart file is deleted. 

Running `flutter generate` again will not regenerate `asset.dart`.

Currently just doing JSON parsing by hand instead of the recommended way but would be great if we can solve this.

**Comment by szotp** [comment]
I think the manual method of generation still works:
```
flutter packages pub run r_flutter:generate --intl-file="lib/resources/i18n/de.arb"
```
it would be nice to document it. Perhaps it could also use config from pubspec instead of command line arguments (intl-file, etc.).

**Comment by kuhnroyal** [comment]
Seems to work when you add it to `dev_dependencies` instead of `builders`.

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.2
  r_flutter: 0.4.1
```
